---
title: "Instrument Variable for Screen Time"
date: 02/06/2024
date-modified: last-modified
date-format: full
categories: [Paper1]
format:
  html:
    page-layout: full
    code-overflow: wrap
comments:
  hypothesis: true
bibliography: references.bib
---

In this update, we try to find an instrument variable to justify the causal effect of screen time on sleep debt. First, we introduce the related variables:

```{python}
#| echo: false
#| warning: false
#| output: true
import time;import pandas as pd;import numpy as np;import datetime
from datetime import datetime;from datetime import timedelta;import sqlite3;import warnings
import matplotlib.pyplot as plt;import seaborn as sns;warnings.filterwarnings('ignore')

df=pd.read_csv("/Users/shaokangyang/Library/CloudStorage/OneDrive-Personal/Nethealth/Data/CNSA/combine/7/bt7_1.5r.csv")

df[['egoid','count_begin90', 'time_fallsleep','battery','battery_time','charging','binterval']]
```

-   **egoid:** individual identifier

-   **count_begin90:** starting time of measurement window of 90 minutes

-   **time_fallsleep:** time of falling asleep for an egoid on a certain day

-   **battery:** battery level at the closest measuring point before the starting point of measurement window, namely "**count_begin90"**

-   **battery_time:** the measuring time point of battery level. We only maintain the observations with '**battery_time' that is within 30 minutes from 'time_fallsleep'** for the purpose of measurement accuracy

-   **charging:** dummy indicating the charging status of smartphone at time 'battery_time' with **'1' for charging and '0' for unpluged**

-   **binterval:** the time interval (minutes) between 'battery_time' and 'count_begin90'

The following table shows descriptive statistics:

```{python}
#| echo: false
#| warning: false
#| output: true

df[['egoid','count_begin90', 'time_fallsleep','battery','charging','battery_time','binterval']].describe()
```

We speculate that the charging status is positively associated with screen time as one may need to charge his/her phone if the user anticipate that he/she was going to use smartphone intensively in the next 90 minutes. To examine whether "charging" could work as and instrument variable for 'screen time", we first regress "screen time" on "charging". Since our earlier results show that screen time has U-shape impact on sleep debt, we divide the data into two subgroups based on the turning point of screen time.

Here is the descriptive statistics for observations before turning point:

```{python}
#| echo: false
#| warning: false
#| output: true
df=pd.read_csv("/Users/shaokangyang/Library/CloudStorage/OneDrive-Personal/Nethealth/Data/CNSA/combine/7/df7_22-5s.csv")
df[['egoid','screen_time', 'unlock','message','count_begin90', 'time_fallsleep','battery','charging','battery_time','binterval']].describe()
```

The following table shows the descriptive statistics for observations after turning point:

```{python}
#| echo: false
#| warning: false
#| output: true
df=pd.read_csv("/Users/shaokangyang/Library/CloudStorage/OneDrive-Personal/Nethealth/Data/CNSA/combine/7/df7_22-5b.csv")
df[['egoid','screen_time', 'unlock','message','count_begin90', 'time_fallsleep','battery','charging','battery_time','binterval']].describe()
```

```{python}
#| echo: false
#| warning: false
#| output: false
import time;import pandas as pd;import numpy as np ;import datetime
from datetime import datetime;from datetime import timedelta;import stata_setup
stata_setup.config('/Applications/Stata', 'mp')
```

## Empiricial Strategy

### Screen Time \< Turning Point

We first check whether charging status could work as an instrument variable for screen time for observations with screen time \< turning point (50 minutes)

```{python}
#| echo: false
#| warning: false
#| output: false
#| code-fold: false
#| code-overflow: wrap
%%stata
#| echo: true
clear all
set maxvar 120000, permanently
set more off

import delimited "/Users/shaokangyang/Library/CloudStorage/OneDrive-Personal/Nethealth/Data/CNSA/combine/7/df7_22-5s.csv"
gen date2 = date(date, "YMD")
```

### **First Stage: Test the Relevance of the Instrument**

```{python}
#| echo: true
#| warning: false
#| output: false
#| code-fold: false
#| code-overflow: wrap
%%stata

global id egoid
global t date2
global ylist sleep_debt
global mainIV  c.screen_time##c.screen_time iimessage unlock
global Call_Control call duration length bytes
global Fitness_Control steps100 floors sedentaryminutes lightlyactiveminutes fairlyactiveminutes veryactiveminutes lowrangecal100 fatburncal100 cardiocal100 peakcal100
global Other_Control naps naps_dur light_exposure insession##weekday##time_wakeuphour c.studyweeks#id
global fe i.studyweeks

*Set data as panel data
sort $id $t
xtset $id $t

regress screen_time charging battery $fe $Fitness_Control $Other_Control $Call_Control message unlock i.egoid

```

```{python}
#| echo: true
#| warning: false
#| output: true
#| code-fold: false
#| code-overflow: wrap
%%stata

esttab, keep(charging battery message unlock) stats(N r2 F p, labels("Observations" "R-squared" "F statistic" "Prob > F")) replace
```

The results shows charging status is positively associated with screen time. Moreover, the F-statistics of 35.34 indicate that 'charging' is a valid IV for screen time.

#### **IV Estimation**

```{python}
#| echo: true
#| warning: false
#| output: false
#| code-fold: false
#| code-overflow: wrap
%%stata

ivregress 2sls sleep_debt (screen_time = charging) $fe $Fitness_Control $Other_Control $Call_Control i.egoid message unlock battery
```

```{python}
#| echo: true
#| warning: false
#| output: true
#| code-fold: false
#| code-overflow: wrap
%%stata

esttab, keep(screen_time battery message unlock) stats(N r2 F p, labels("Observations" "R-squared" "F statistic" "Prob > F")) replace
```

The IV estimation results suggest that screen time reduces sleep debt when screen time \< turning point. \### Screen Time \> Turning Point

We first check whether charging status could work as an instrument variable for screen time for observations with screen time \< turning point (50 minutes)

```{python}
#| echo: false
#| warning: false
#| output: false
#| code-fold: false
#| code-overflow: wrap
%%stata
#| echo: true
clear all
set maxvar 120000, permanently
set more off

import delimited "/Users/shaokangyang/Library/CloudStorage/OneDrive-Personal/Nethealth/Data/CNSA/combine/7/df7_22-5b.csv"
gen date2 = date(date, "YMD")
```

### **First Stage: Test the Relevance of the Instrument**

```{python}
#| echo: true
#| warning: false
#| output: false
#| code-fold: false
#| code-overflow: wrap
%%stata

global id egoid
global t date2
global ylist sleep_debt
global mainIV  c.screen_time##c.screen_time iimessage unlock
global Call_Control call duration length bytes
global Fitness_Control steps100 floors sedentaryminutes lightlyactiveminutes fairlyactiveminutes veryactiveminutes lowrangecal100 fatburncal100 cardiocal100 peakcal100
global Other_Control naps naps_dur light_exposure insession##weekday##time_wakeuphour c.studyweeks#id
global fe i.studyweeks

*Set data as panel data
sort $id $t
xtset $id $t

regress screen_time charging battery $fe $Fitness_Control $Other_Control $Call_Control message unlock i.egoid

```

```{python}
#| echo: true
#| warning: false
#| output: true
#| code-fold: false
#| code-overflow: wrap
%%stata

esttab, keep(charging battery message unlock) stats(N r2 F p, labels("Observations" "R-squared" "F statistic" "Prob > F")) replace
```

The results shows charging status is positively associated with screen time, indicating that 'charging' is a valid IV for screen time.

#### **IV Estimation**

```{python}
#| echo: true
#| warning: false
#| output: false
#| code-fold: false
#| code-overflow: wrap
%%stata

ivregress 2sls sleep_debt (screen_time = charging) $fe $Fitness_Control $Other_Control $Call_Control i.egoid message unlock battery
```

```{python}
#| echo: true
#| warning: false
#| output: true
#| code-fold: false
#| code-overflow: wrap
%%stata

esttab, keep(screen_time battery message unlock) stats(N r2 F p, labels("Observations" "R-squared" "F statistic" "Prob > F")) replace
```

The estimation for screen time is significant when p\<0.1 although not significant when p\<0.05. The IV estimation results suggest that screen time increases sleep debt when screen time \> turning point.
