project:
  type: website
  output-dir: docs
website:
  favicon: Virginia_Tech_seal.svg.png
  image: Horizontal_VT_Full_Color_RGB.png

  # sidebar:
  #   contents:
  #   tools:
  #     - icon: github
  #       href: https://github.com/Shaokang-Yang

  navbar:
    #title: My Website
    pinned: true
    logo: Horizontal_VT_Full_Color_RGB.png
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - project.qmd # add your posts.qmd file to your navbar!
      - icon: github
        href: https://github.com/Shaokang-Yang
      - icon: linkedin
        href: https://www.linkedin.com/in/shaokang-y-52b633162/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    grid:
      sidebar-width: 350px
resource-files:
  - pdfs/*
body-header: | 
  This page brought to you by <https://example.com>
#margin-header: |
  #![](/Horizontal_VT_Full_Color_RGB.png)





