---
title: "Research"
format:
  html:
    css: styles2.css
class: custom-font-pos
---

## Research Interests

-   **Topics:** Artificial intelligence (AI) for Behavioral Decision-making,  Technology policy evaluation, Digital technologies, Economics of AI 
-   **Methodologies:** Applied econometrics, experiments, machine learning, LLM, Causal AI

## Research

### Digital Technologies and Well-being

1. **Smartphone Use, Social Support, and Sleep Health.** Shaokang Yang, Idris Adjerid. [SSRN](http://dx.doi.org/10.2139/ssrn.5368531) — *Under Review at **Information Systems Research***  
   - Accepted to WISE, Nashville, TN, Dec 17–19, 2025  
   - Accepted to Conference on Health IT and Analytics (CHITA), Washington, DC, May 2024  
   - Presented at Doctoral Consortium of CHITA, Washington, DC, May 2024  
   - Presented at 33rd Annual POMS Conference, Orlando, FL, May 2023  
   - Accepted to CHITA, Washington, DC, May 2023  

2. **Friends over Feeds: How Social Smartphone Use Reduces Screen Time.** Shaokang Yang, Idris Adjerid. — *In preparation for submission (target: **Organization Science**)*  
   - Scheduled at INFORMS, Atlanta, GA, Oct 28, 2025  
   - Accepted to CHITA, Austin, TX, Apr 2025  
   - Presented at INFORMS Annual Meeting, Seattle, WA, Oct 2024  

3. **Pet Ownership and Mental Health During the Pandemic: Evidence from an E-Commerce Platform.** Li Lin, Shaokang Yang. — *Data collection phase*  

---

### Public Policy Evaluation on Health IT

1. **The Abortion War: When Restrictions Meet Technology.** Shaokang Yang, Idris Adjerid. — *Data collected, working on empirical analysis*  
2. **Pro-Choice Vs Pro-Life: The Impact of Healthcare Digitalization on Infant Mortality.** Shaokang Yang. — *Data collected, working on empirical analysis*  

---

### AI for Behavioral Decision-making

1. **Prevention is Better Than Cure: Artificial Intelligence-based Nudging to Prevent Digital Addiction.** — *Ideation phase*  


## Talks

-   Shaokang Yang, Idris Adjerid. *Smartphone Use, Social Support, and Sleep Health.* **Workshop on Information Systems and Economics (WISE)**, Nashville, TN, Dec 17--19, 2025.

-   Shaokang Yang, Idris Adjerid. *Friends over Feeds: How Social Smartphone Use Reduces Screen Time.* **Scheduled on INFORMS Annual Meeting **, Atlanta, GA, 2:09 PM – 2:27 PM, Oct 28, 2025.

-   Shaokang Yang, Idris Adjerid. *Friends over Feeds: How Social Smartphone Use Reduces Screen Time.* *Conference on Health IT and Analytics (CHITA)*, Austin, TX, Apr 2025.

-   Shaokang Yang, Idris Adjerid. *Friends over Feeds: How Social Smartphone Use Reduces Screen Time.* *INFORMS Annual Meeting*, Seattle, WA, Oct 2024.

-   Shaokang Yang, Idris Adjerid. *Smartphone Use, Social Support, and Sleep Health.* *Conference on Health IT and Analytics (CHITA)*, Washington, DC, May 2024.

-   Shaokang Yang, Idris Adjerid. *Friends over Feeds: How Social Smartphone Use Reduces Screen Time.* *Doctoral Consortium of CHITA*, Washington, DC, May 2024.

-   Shaokang Yang, Idris Adjerid. *Smartphone Use, Social Support, and Sleep Health.* *33rd Annual POMS Conference*, Orlando, FL, May 2023.

-   Shaokang Yang, Idris Adjerid. *Smartphone Use, Social Support, and Sleep Health.* *Conference on Health IT and Analytics (CHITA)*, Washington, DC, May 2023.
