{
  "hash": "c44d570a52400705a46630a41f030a42",
  "result": {
    "markdown": "---\ntitle: \"Network Overlapping\"\ndate: 01/29/2024\ndate-modified: last-modified\ndate-format: full\ncategories: [Paper2]\n#image: \"cluster1.png\"\ntbl-colwidths: [5,30,125]\nformat: \n  html:\n    page-layout: full\n---\n\nSince participants report their network contacts over social network survey, some contacts may be repteatedly reprted in multiple surveys. To understand whether students' social network survey are cumulative or aggregated over time, in this blog, we exmaine the overlapping rate of reported contacts.\n\nThe following figure shows how many waves of surveys participants have ever joined.\n\n![](images/paste-1.png)\n\nFor example, 78 participants completed 6 surveys.\n\n\n\nThe following table shows the social network summary of participant \"10237\".\n\n::: {.cell execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\n egoid  wave  surveys  contacts  total_contacts  participation_rate                                                                                                                      contact_ids                                                         overlap_contacts  overlap\n 10237     1        7        10              43            0.232558                                                 {715237, 710213, 944646, 201164, 970860, 606285, 794543, 555957, 791455, 395167}                                                                    set() 0.000000\n 10237     2        7         6              43            0.139535                                                                                 {927336, 760234, 549070, 519415, 791455, 395167}                                                         {395167, 791455} 0.333333\n 10237     3        7        13              43            0.302326                         {390853, 189158, 982757, 349320, 899046, 760234, 609614, 857038, 525361, 230359, 789561, 427966, 193183}                                                                 {760234} 0.076923\n 10237     4        7        10              43            0.232558                                                 {390853, 982757, 899046, 349320, 760234, 857038, 609614, 824506, 802525, 277215}                 {982757, 390853, 899046, 349320, 760234, 857038, 609614} 0.700000\n 10237     5        7        16              43            0.372093 {524225, 669474, 993411, 390853, 899046, 881384, 195368, 760234, 438507, 431884, 549070, 193183, 277215, 791455, 869629, 395167}                                         {760234, 390853, 899046, 277215} 0.250000\n 10237     6        7        15              43            0.348837         {669474, 390853, 486534, 293830, 530826, 760234, 438507, 880589, 549070, 193183, 277215, 466934, 791455, 904250, 395167} {669474, 390853, 760234, 438507, 549070, 277215, 791455, 395167, 193183} 0.600000\n 10237     7        7         6              43            0.139535                                                                                 {982757, 486534, 760234, 609614, 824506, 193183}                                                 {760234, 486534, 193183} 0.500000\n```\n:::\n:::\n\n\n-   **egoid:** individual identifier;\n\n-   **wave:** survey identifier;\n\n-   **surveys:** the number of surveys the participant completed;\n\n-   **contacts:** the number of contacts reported in the current survey;\n\n-   **total contacts:** the number of contacts reported in total survey;\n\n-   **participation_rate:** contacts/total contacts;\n\n-   **contact_ids:** the identifiers of contacts reported in the current survey;\n\n-   **overlap:** the overlapping rate of contacts of previous and current survey, which is calculated as: the number of contacts reported both by the previous and current surveys / the number of contacts in the current survey.\n\nIn the survey of wave 2, contacts \"**395167(Sibling), 791455(Sibling)**\" has been reported in the survey of wave 1, the overlap rate is 2/6=0.33.\n\nIn the survey of wave 3, contacts **\"760234\"(Romantic Partner)** has been reported in the survey of wave 2, the overlap rate is 1/13=0.076.\n\nIn the survey of wave 4, contacts \"**982757(Sibling), 390853(Friend), 899046(Stepsibling/Friend), 349320(Friend), 760234(Romantic Partner), 857038(Romantic Partner/OtherFamily), 609614(Parent)**\" has been reported in the survey of wave 3, the overlap rate is 7/10=0.70.\n\nIn the survey of wave 5, contacts \" **760234(Romantic Partner), 390853(Friend), 899046(Stepsibling/Friend),, 277215(Friend)**\" has been reported in the survey of wave 4, the overlap rate is 4/16=0.25.\n\nIn the survey of wave 6, contacts \" **669474(Friend), 390853(Friend), 760234(Romantic Partner), 438507(Friend), 549070(Parent), 277215(Friend), 791455(Sibling), 395167(Sibling), 193183(Friend)**\" has been reported in the survey of wave 5, the overlap rate is 9/15=0.60.\n\nIn the survey of wave 7, contacts \" **760234(Romantic Partner), 486534(Friend), 193183(Friend)**\" has been reported in the survey of wave 6, the overlap rate is 3/6=0.50.\n\nThe following table shows the descriptive summary for all participants (Person $⨯$ Wave of Survey)\n\n::: {.cell execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>egoid</th>\n      <th>vertex1</th>\n      <th>wave</th>\n      <th>surveys</th>\n      <th>contacts</th>\n      <th>total_contacts</th>\n      <th>participation_rate</th>\n      <th>overlap</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>2979.000000</td>\n      <td>2979.000000</td>\n      <td>2979.000000</td>\n      <td>2979.000000</td>\n      <td>2979.000000</td>\n      <td>2979.000000</td>\n      <td>2979.000000</td>\n      <td>2979.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>54811.522323</td>\n      <td>114008.924136</td>\n      <td>3.785834</td>\n      <td>5.618328</td>\n      <td>12.047667</td>\n      <td>34.428332</td>\n      <td>0.391431</td>\n      <td>0.395416</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>26008.010124</td>\n      <td>183801.840091</td>\n      <td>2.163821</td>\n      <td>2.116411</td>\n      <td>6.120111</td>\n      <td>16.537434</td>\n      <td>0.213036</td>\n      <td>0.344069</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>10115.000000</td>\n      <td>10115.000000</td>\n      <td>1.000000</td>\n      <td>1.000000</td>\n      <td>1.000000</td>\n      <td>1.000000</td>\n      <td>0.022222</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>31439.000000</td>\n      <td>34203.000000</td>\n      <td>2.000000</td>\n      <td>4.000000</td>\n      <td>7.000000</td>\n      <td>22.000000</td>\n      <td>0.250000</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>53518.000000</td>\n      <td>60396.000000</td>\n      <td>3.000000</td>\n      <td>6.000000</td>\n      <td>11.000000</td>\n      <td>32.000000</td>\n      <td>0.344828</td>\n      <td>0.411765</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>77621.500000</td>\n      <td>88185.000000</td>\n      <td>5.000000</td>\n      <td>7.000000</td>\n      <td>17.000000</td>\n      <td>44.000000</td>\n      <td>0.483871</td>\n      <td>0.692308</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>99978.000000</td>\n      <td>998789.000000</td>\n      <td>8.000000</td>\n      <td>8.000000</td>\n      <td>25.000000</td>\n      <td>83.000000</td>\n      <td>1.000000</td>\n      <td>1.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}